alert('Hello, Koki!');
alert(1+1);
alert(Math.sqrt(1+1));
alert("√2 + √3 ≈ " + (Math.sqrt(2) + Math.sqrt(3)));
alert("1 ÷ 0 = 定義されません");
alert("0 ÷ 0 = 定義されません（不定形）");
alert(2+3);
alert('2'+'3');
alert(Number('2')+Number('3'));
alert('2'+3);
alert(Number('2')+3);
